namespace MassLab.Common.Api.Models;

/// <summary>
/// Represents a standardized error response following RFC 7807 Problem Details specification.
/// </summary>
public class ProblemDetailsResponse
{
    /// <summary>
    /// A URI reference that identifies the problem type.
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// The HTTP status code generated by the origin server.
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string Detail { get; set; } = string.Empty;

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    public string Instance { get; set; } = string.Empty;

    /// <summary>
    /// The trace identifier for correlation across distributed systems.
    /// </summary>
    public string TraceId { get; set; } = string.Empty;

    /// <summary>
    /// Field-level validation errors (optional, used for validation failures).
    /// </summary>
    public IDictionary<string, string[]>? Errors { get; set; }
}
